/**
 * T310 — Canonical error catalogue.
 * Maps every known code to its default HTTP status so callers never have to
 * hard-code status numbers — just pass the code and let the map decide.
 * Unknown codes fall through to 500 so new errors are safely catchable.
 */
export const SCHOOL_ERROR_STATUS: Readonly<Record<string, number>> = {
  // Auth
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,

  // Not found
  SCHOOL_NOT_FOUND: 404,
  USER_NOT_FOUND: 404,
  ATHLETE_NOT_FOUND: 404,
  COACH_PROFILE_NOT_FOUND: 404,
  TEAM_NOT_FOUND: 404,
  WORKOUT_NOT_FOUND: 404,
  WORKOUT_TEMPLATE_NOT_FOUND: 404,
  INVITATION_NOT_FOUND: 404,
  HISTORY_GRANT_NOT_FOUND: 404,
  STORE_NOT_FOUND: 404,
  EVALUATION_NOT_FOUND: 404,
  EXECUTION_NOT_FOUND: 404,
  COACH_ATHLETE_ASSIGNMENT_NOT_FOUND: 404,

  // Conflict / state
  SCHOOL_INACTIVE: 409,
  SCHOOL_ALREADY_EXISTS: 409,
  SCHOOL_ATHLETE_MEMBERSHIP_ALREADY_ACTIVE: 409,
  SCHOOL_ATHLETE_MEMBERSHIP_PENDING: 409,
  SCHOOL_ATHLETE_MEMBERSHIP_NOT_ACTIVE: 409,
  COACH_SCHOOL_MEMBERSHIP_ALREADY_ACTIVE: 409,
  COACH_SCHOOL_MEMBERSHIP_CONFLICT: 409,
  COACH_SCHOOL_MEMBERSHIP_NOT_ACTIVE: 409,
  COACH_ATHLETE_ASSIGNMENT_CONFLICT: 409,
  ATHLETE_NOT_MEMBER: 409,
  ATHLETE_ALREADY_IN_TEAM: 409,
  ATHLETE_NOT_IN_TEAM: 409,
  COACH_ALREADY_IN_TEAM: 409,
  COACH_NOT_IN_TEAM: 409,
  TEAM_ALREADY_ARCHIVED: 409,
  TEAM_ARCHIVED: 409,
  TEAM_EMPTY: 409,
  TEAM_NOT_IN_SCHOOL: 409,
  INVITATION_REVOKED: 409,
  INVITATION_EXPIRED: 409,
  INVITATION_EXHAUSTED: 409,
  INVITATION_CREATE_CONFLICT: 409,
  HISTORY_GRANT_NOT_ACTIVE: 409,
  HISTORY_GRANT_CREATE_CONFLICT: 409,
  HISTORY_GRANT_REVOKE_CONFLICT: 409,
  HISTORY_GRANT_UPDATE_CONFLICT: 409,
  WORKOUT_ASSIGN_CONFLICT: 409,
  WORKOUT_CREATE_CONFLICT: 409,
  WORKOUT_INVALID_PERIOD: 409,
  WORKOUT_INVALID_TRANSITION: 409,
  WORKOUT_NOT_ASSIGNABLE: 409,
  WORKOUT_TEMPLATE_CREATE_CONFLICT: 409,
  WORKOUT_TEMPLATE_UPDATE_CONFLICT: 409,
  WORKOUT_TEMPLATE_INVALID_TIMESTAMP: 409,
  WORKOUT_TEMPLATE_NOT_ACTIVE: 409,
  EVALUATION_ALREADY_EXISTS: 409,
  EXECUTION_INVALID_TRANSITION: 409,
  EXECUTION_NOT_EVALUABLE: 409,
  MATCHING_CONFLICT: 409,

  // Validation
  INVALID_INPUT: 422,
  HISTORY_GRANT_INVALID_TIMESTAMP: 422,
  INVITATION_INVALID_EXPIRATION: 422,

  // Server / unknown
  SYSTEM: 500,
  ACTIVE: 500,
} as const;

export class SchoolError extends Error {
  readonly status: number;

  constructor(
    readonly code: string,
    message: string,
    /** Optional override — defaults to the catalogue value, then 500. */
    status?: number,
  ) {
    super(message);
    this.name = "SchoolError";
    this.status = status ?? SCHOOL_ERROR_STATUS[code] ?? 500;
  }
}
