/**
 * T310 — Canonical error catalogue.
 * Maps every known code to its default HTTP status so callers never have to
 * hard-code status numbers — just pass the code and let the map decide.
 * Unknown codes fall through to 500 so new errors are safely catchable.
 */
export const SCHOOL_ERROR_STATUS: Readonly<Record<string, number>> = {
  // Auth
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,

  // Not found
  SCHOOL_NOT_FOUND: 404,
  USER_NOT_FOUND: 404,
  ATHLETE_NOT_FOUND: 404,
  COACH_PROFILE_NOT_FOUND: 404,
  TEAM_NOT_FOUND: 404,
  WORKOUT_NOT_FOUND: 404,
  WORKOUT_TEMPLATE_NOT_FOUND: 404,
  INVITATION_NOT_FOUND: 404,
  HISTORY_GRANT_NOT_FOUND: 404,
  STORE_NOT_FOUND: 404,
  EVALUATION_NOT_FOUND: 404,
  EXECUTION_NOT_FOUND: 404,
  COACH_ATHLETE_ASSIGNMENT_NOT_FOUND: 404,
  WORKOUT_REQUEST_NOT_FOUND: 404,
  WORKOUT_CHANGE_REQUEST_NOT_FOUND: 404,
  SCHOOL_MEMBERSHIP_NOT_FOUND: 404,
  SCHOOL_MEMBERSHIP_ROLE_NOT_FOUND: 404,
  COACH_SCHOOL_MEMBERSHIP_NOT_FOUND: 404,

  // Marketplace (TM012) — PRODUCT_NOT_FOUND/PRODUCT_NOT_AVAILABLE/etc. were
  // already thrown by CreateTrainingPurchase (T405) with an explicit status
  // at each call site; registered here too so the catalogue is the single
  // source of truth and future call sites can omit the explicit status.
  PRODUCT_NOT_FOUND: 404,
  VERSION_NOT_FOUND: 404,
  LICENSE_NOT_FOUND: 404,
  PRODUCT_VISIBILITY_DENIED: 404,
  // Onda 3 — acompanhamento independente (TM072-081, RF-301-305)
  ENGAGEMENT_NOT_FOUND: 404,
  ADAPTATION_NOT_FOUND: 404,
  WORKOUT_ASSIGNMENT_NOT_FOUND: 404,

  // Marketplace — coach studio (TM018–TM023)
  WORKOUT_TEMPLATE_NOT_ACCESSIBLE: 403,

  // Conflict / state
  SCHOOL_INACTIVE: 409,
  SCHOOL_ALREADY_EXISTS: 409,
  SCHOOL_ATHLETE_MEMBERSHIP_ALREADY_ACTIVE: 409,
  SCHOOL_ATHLETE_MEMBERSHIP_PENDING: 409,
  SCHOOL_ATHLETE_MEMBERSHIP_NOT_ACTIVE: 409,
  COACH_SCHOOL_MEMBERSHIP_ALREADY_ACTIVE: 409,
  COACH_SCHOOL_MEMBERSHIP_CONFLICT: 409,
  COACH_SCHOOL_MEMBERSHIP_NOT_ACTIVE: 409,
  COACH_SCHOOL_MEMBERSHIP_SUSPENDED: 409,
  COACH_ATHLETE_ASSIGNMENT_CONFLICT: 409,
  ATHLETE_NOT_MEMBER: 409,
  ATHLETE_ALREADY_IN_TEAM: 409,
  ATHLETE_NOT_IN_TEAM: 409,
  COACH_ALREADY_IN_TEAM: 409,
  COACH_NOT_IN_TEAM: 409,
  TEAM_ALREADY_ARCHIVED: 409,
  TEAM_ARCHIVED: 409,
  TEAM_CAPACITY_EXCEEDED: 409,
  TEAM_EMPTY: 409,
  TEAM_NOT_IN_SCHOOL: 409,
  INVITATION_REVOKED: 409,
  INVITATION_EXPIRED: 409,
  INVITATION_EXHAUSTED: 409,
  INVITATION_CREATE_CONFLICT: 409,
  HISTORY_GRANT_NOT_ACTIVE: 409,
  HISTORY_GRANT_CREATE_CONFLICT: 409,
  HISTORY_GRANT_REVOKE_CONFLICT: 409,
  HISTORY_GRANT_UPDATE_CONFLICT: 409,
  WORKOUT_ASSIGN_CONFLICT: 409,
  WORKOUT_CREATE_CONFLICT: 409,
  WORKOUT_INVALID_PERIOD: 409,
  WORKOUT_INVALID_TRANSITION: 409,
  WORKOUT_NOT_ASSIGNABLE: 409,
  WORKOUT_TEMPLATE_CREATE_CONFLICT: 409,
  WORKOUT_TEMPLATE_UPDATE_CONFLICT: 409,
  WORKOUT_TEMPLATE_INVALID_TIMESTAMP: 409,
  WORKOUT_TEMPLATE_NOT_ACTIVE: 409,
  EVALUATION_ALREADY_EXISTS: 409,
  EXECUTION_INVALID_TRANSITION: 409,
  EXECUTION_NOT_EVALUABLE: 409,
  MATCHING_CONFLICT: 409,
  WORKOUT_LOG_CONFLICT: 409,
  WORKOUT_REQUEST_NOT_PENDING: 409,
  WORKOUT_REQUEST_CREATE_CONFLICT: 409,
  WORKOUT_REQUEST_FULFILL_CONFLICT: 409,
  WORKOUT_CHANGE_REQUEST_ALREADY_OPEN: 409,
  WORKOUT_CHANGE_REQUEST_NOT_OPEN: 409,
  WORKOUT_CHANGE_REQUEST_NO_COACH: 409,
  WORKOUT_CHANGE_REQUEST_CONFLICT: 409,
  SCHOOL_MEMBERSHIP_ALREADY_EXISTS: 409,
  SCHOOL_MEMBERSHIP_NOT_ACTIVE: 409,
  SCHOOL_MEMBERSHIP_ROLE_ALREADY_EXISTS: 409,
  SCHOOL_MEMBERSHIP_LAST_ROLE: 409,
  SCHOOL_MEMBERSHIP_CONFLICT: 409,
  SCHOOL_OWNER_PROTECTED: 409,
  SCHOOL_LAST_OWNER: 409,
  PRODUCT_NOT_AVAILABLE: 409,
  PRODUCT_NO_VERSION: 409,
  // TM038 — a paid product (priceCents != null) rejected by the free-only
  // acquisition path (RF-108); distinct from PRODUCT_NOT_AVAILABLE (status/
  // visibility gate) so the client can tell "not for sale" from "not free".
  PRODUCT_NOT_FREE: 409,
  LICENSE_NOT_ACTIVE: 409,
  LICENSE_ALREADY_ACTIVE: 409,
  PURCHASE_IDEMPOTENCY_CONFLICT: 409,
  REVIEW_ALREADY_EXISTS: 409,
  ENGAGEMENT_ALREADY_ACTIVE: 409,
  ADAPTATION_VERSION_CONFLICT: 409,
  // Onda 3 — acompanhamento independente (TM072-081, RF-301-305)
  ENGAGEMENT_SCOPE_CONFLICT: 409,
  ENGAGEMENT_NOT_PENDING: 409,
  ADAPTATION_NOT_PENDING: 409,
  // TM020 — optimistic concurrency on TrainingProduct draft edits (RNF-003):
  // `expectedVersion` (the product's `updatedAt` as last read by the client)
  // no longer matches what is stored.
  PRODUCT_UPDATE_CONFLICT: 409,

  // Validation
  INVALID_INPUT: 422,
  HISTORY_GRANT_INVALID_TIMESTAMP: 422,
  INVITATION_INVALID_EXPIRATION: 422,
  WORKOUT_LOG_INVALID_DATE: 422,
  PAYMENT_REF_REQUIRED: 422,
  ENGAGEMENT_INVALID_TARGET: 422,

  // Bad request — malformed/untrusted input rejected before touching domain state.
  INVALID_CALLBACK_URL: 400,
  // TM061 — invalid/missing Stripe-Signature; rejected before any DB touch.
  WEBHOOK_SIGNATURE_INVALID: 400,

  // Authorization (marketplace: eligibility failures that are not "no session", RF-112)
  REVIEW_NOT_ELIGIBLE: 403,

  // Server / unknown
  SYSTEM: 500,
  ACTIVE: 500,
} as const;

export class SchoolError extends Error {
  readonly status: number;

  constructor(
    readonly code: string,
    message: string,
    /** Optional override — defaults to the catalogue value, then 500. */
    status?: number,
  ) {
    super(message);
    this.name = "SchoolError";
    this.status = status ?? SCHOOL_ERROR_STATUS[code] ?? 500;
  }
}
