/** Public boundary for the school domain. */
export { AssignmentStatus, CoachStatus } from "./domain/enums";
export { InvitationType, InvitationStatus, InvitationUseResult } from "./domain/enums";
export { HistoryGranteeType, HistoryGrantStatus } from "./domain/enums";
export { historyGrantScopeSchema, historyAccessGrantSchema, createHistoryAccessGrant } from "./domain/history-access-grant";
export type { HistoryGrantScope, HistoryAccessGrant, CreateHistoryAccessGrantInput } from "./domain/history-access-grant";
export { historyAccessGrantedSchema, createHistoryAccessGranted } from "./domain/history-access-granted";
export type { HistoryAccessGranted } from "./domain/history-access-granted";
export { historyAccessRevokedSchema, createHistoryAccessRevoked } from "./domain/history-access-revoked";
export type { HistoryAccessRevoked } from "./domain/history-access-revoked";
export { GrantHistoryAccess, grantHistoryAccessSchema } from "./application/grant-history-access";
export { UpdateHistoryGrant, updateHistoryGrantSchema } from "./application/update-history-grant";
export { RevokeHistoryAccess, revokeHistoryAccessSchema } from "./application/revoke-history-access";
export { CheckHistoryAccess, checkHistoryAccessSchema } from "./application/check-history-access";
export { CanReadAthleteCurrentData, currentAthleteDataContextSchema } from "./application/can-read-athlete-current-data";
export { CanReadAthleteHistory, athleteHistoryContextSchema } from "./application/can-read-athlete-history";
export { invitationLinkSchema, createInvitationLink } from "./domain/invitation-link";
export { CreateInvitationLink, createInvitationLinkSchema } from "./application/create-invitation-link";
export { ResolveInvitationLink, resolveInvitationLinkSchema } from "./application/resolve-invitation-link";
export { AcceptInvitation, acceptInvitationSchema } from "./application/accept-invitation";
export { SearchSchools, searchSchoolsSchema } from "./application/search-schools";
export { RevokeInvitation, revokeInvitationSchema } from "./application/revoke-invitation";
export { ExpireInvitations } from "./application/expire-invitations";
export type { InvitationLink, CreateInvitationLinkInput } from "./domain/invitation-link";
export { coachProfileSchema, createCoachProfile } from "./domain/coach-profile";
export type { CoachProfile, CreateCoachProfileInput } from "./domain/coach-profile";
export { CoachProfileService } from "./application/coach-profile-service";
export { coachSchoolMembershipSchema, createCoachSchoolMembership, transitionCoachSchoolMembership } from "./domain/coach-school-membership";
export type { CoachSchoolMembership, CreateCoachSchoolMembershipInput } from "./domain/coach-school-membership";
export { schoolAthleteMembershipSchema, createSchoolAthleteMembership, transitionSchoolAthleteMembership } from "./domain/school-athlete-membership";
export type { SchoolAthleteMembership, CreateSchoolAthleteMembershipInput } from "./domain/school-athlete-membership";
export { coachAthleteAssignmentSchema, createCoachAthleteAssignment, transitionCoachAthleteAssignment } from "./domain/coach-athlete-assignment";
export type { CoachAthleteAssignment, CreateCoachAthleteAssignmentInput } from "./domain/coach-athlete-assignment";
export { coachAssignedToAthleteSchema, createCoachAssignedToAthlete } from "./domain/coach-assigned-to-athlete";
export type { CoachAssignedToAthlete } from "./domain/coach-assigned-to-athlete";
export { athleteEnteredLobbySchema, createAthleteEnteredLobby } from "./domain/athlete-entered-lobby";
export type { AthleteEnteredLobby, CreateAthleteEnteredLobbyInput } from "./domain/athlete-entered-lobby";
export { coachLeftSchoolSchema, createCoachLeftSchool } from "./domain/coach-left-school";
export type { CoachLeftSchool } from "./domain/coach-left-school";
export { RemoveSchoolMember } from "./application/remove-school-member";
export { AddRoleToMember, addRoleToMemberSchema } from "./application/add-role-to-member";
export { RemoveRoleFromMember, removeRoleFromMemberSchema } from "./application/remove-role-from-member";
export { CanManageSchool } from "./application/can-manage-school";
export { CanManageMembers } from "./application/can-manage-members";
export { CanDeactivateSchool } from "./application/can-deactivate-school";
export { ApproveCoachSchoolMembership } from "./application/approve-coach-school-membership";
export { ApproveAthleteMembership } from "./application/approve-athlete-membership";
export { WorkoutOwnerType, TemplateStatus, WorkoutStatus, WorkoutBlockType } from "./domain/enums";
export { workoutTemplateSchema, createWorkoutTemplate } from "./domain/workout-template";
export type { WorkoutTemplate, CreateWorkoutTemplateInput } from "./domain/workout-template";
export { workoutSchema, workoutSnapshotSchema, createWorkout, createWorkoutSnapshot } from "./domain/workout";
export type { Workout, WorkoutSnapshot, CreateWorkoutInput } from "./domain/workout";
export { workoutBlockSchema, createWorkoutBlock } from "./domain/workout-block";
export type { WorkoutBlock, CreateWorkoutBlockInput } from "./domain/workout-block";
export { WorkoutTemplateRepository } from "./infrastructure/workout-template-repository";
export { WorkoutRepository } from "./infrastructure/workout-repository";
